- hosts: all
  tasks:
  - name: Docker repository
    yum_repository:
       name: "docker"
       description: "Docker yum Repo"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
       gpgcheck: no
  - name: Install Docker
    command: "yum -y install docker-ce --nobest" 
  - name: Start Docker service
    service:
       name: "docker"
       state: started
  - name: Install python3
    package:
            name: "python3"
            state: present
  - name: Install Docker Module for Python
    pip:
       name: docker
  - name: Pull docker image
    docker_image:
           name: "httpd"
           source: pull
  - name: Making a directory on managed node
    file:
          path: "/root/docker_ws"
          state: directory
  - name: Copying webpage to managed node directory
    copy:
          src: "my.html"
          dest: "/root/docker_ws"
  - name: Create a data container
    docker_container:
          name: "my_os"
          image: "httpd"
          volumes:
               - "/root/docker_ws:/usr/local/apache2/htdocs/"
          ports:
               - "5678:80"
          state: started
